---
- name: Achmea TechDay playbook
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: rpm

    - name: Include nginx from the collection
      ansible.builtin.include_role:
        name: achmea.hello_techday.nginx
